// Tradução dos nomes dos times (seleções) que vêm da API football-data.org
// (em inglês) para português. A API às vezes usa variações de nome
// (ex: "Korea Republic" vs "South Korea", "Côte d'Ivoire" vs "Ivory Coast"),
// então incluímos as variações conhecidas como chaves apontando pro mesmo valor.
//
// Cobre as seleções da Copa do Mundo 2026 (48 vagas) e demais seleções que
// costumam aparecer nas eliminatórias, garantindo tradução mesmo antes da
// definição final dos classificados.
const TRADUCOES: Record<string, string> = {
  // Anfitriões
  Canada: "Canadá",
  Mexico: "México",
  "United States": "Estados Unidos",
  USA: "Estados Unidos",

  // América do Sul (CONMEBOL)
  Argentina: "Argentina",
  Brazil: "Brasil",
  Uruguay: "Uruguai",
  Colombia: "Colômbia",
  Ecuador: "Equador",
  Paraguay: "Paraguai",
  Peru: "Peru",
  Chile: "Chile",
  Bolivia: "Bolívia",
  Venezuela: "Venezuela",

  // Europa (UEFA)
  Germany: "Alemanha",
  France: "França",
  Spain: "Espanha",
  England: "Inglaterra",
  Portugal: "Portugal",
  Italy: "Itália",
  Netherlands: "Holanda",
  Belgium: "Bélgica",
  Croatia: "Croácia",
  Switzerland: "Suíça",
  Denmark: "Dinamarca",
  Poland: "Polônia",
  Austria: "Áustria",
  Sweden: "Suécia",
  Serbia: "Sérvia",
  Ukraine: "Ucrânia",
  Wales: "País de Gales",
  Scotland: "Escócia",
  Norway: "Noruega",
  Turkey: "Turquia",
  "Türkiye": "Turquia",
  "Czech Republic": "República Tcheca",
  Czechia: "República Tcheca",
  Hungary: "Hungria",
  Romania: "Romênia",
  Greece: "Grécia",
  Slovakia: "Eslováquia",
  Slovenia: "Eslovênia",
  Ireland: "Irlanda",
  "Republic of Ireland": "Irlanda",
  "Northern Ireland": "Irlanda do Norte",
  Iceland: "Islândia",
  Finland: "Finlândia",
  "Bosnia and Herzegovina": "Bósnia e Herzegovina",
  Albania: "Albânia",
  "North Macedonia": "Macedônia do Norte",
  Georgia: "Geórgia",
  Russia: "Rússia",
  Montenegro: "Montenegro",
  Kosovo: "Kosovo",
  Luxembourg: "Luxemburgo",
  Bulgaria: "Bulgária",
  Israel: "Israel",
  Armenia: "Armênia",
  Azerbaijan: "Azerbaijão",
  Belarus: "Bielorrússia",
  Estonia: "Estônia",
  Latvia: "Letônia",
  Lithuania: "Lituânia",
  Moldova: "Moldávia",
  Cyprus: "Chipre",
  Malta: "Malta",
  "Faroe Islands": "Ilhas Faroé",
  Gibraltar: "Gibraltar",
  Andorra: "Andorra",
  "San Marino": "San Marino",
  Liechtenstein: "Liechtenstein",

  // África (CAF)
  Morocco: "Marrocos",
  Senegal: "Senegal",
  Tunisia: "Tunísia",
  Algeria: "Argélia",
  Egypt: "Egito",
  Nigeria: "Nigéria",
  Cameroon: "Camarões",
  Ghana: "Gana",
  "Ivory Coast": "Costa do Marfim",
  "Côte d'Ivoire": "Costa do Marfim",
  "Cote d'Ivoire": "Costa do Marfim",
  Mali: "Mali",
  "Burkina Faso": "Burkina Faso",
  "South Africa": "África do Sul",
  "Cape Verde": "Cabo Verde",
  "Cabo Verde": "Cabo Verde",
  "DR Congo": "Rep. Dem. do Congo",
  "Congo DR": "Rep. Dem. do Congo",
  "Democratic Republic of the Congo": "Rep. Dem. do Congo",
  Congo: "Congo",
  Gabon: "Gabão",
  Angola: "Angola",
  Zambia: "Zâmbia",
  Zimbabwe: "Zimbábue",
  Uganda: "Uganda",
  Kenya: "Quênia",
  Tanzania: "Tanzânia",
  Mozambique: "Moçambique",
  Guinea: "Guiné",
  "Guinea-Bissau": "Guiné-Bissau",
  "Equatorial Guinea": "Guiné Equatorial",
  Benin: "Benin",
  Togo: "Togo",
  Namibia: "Namíbia",
  Madagascar: "Madagascar",
  Mauritania: "Mauritânia",
  Libya: "Líbia",
  Sudan: "Sudão",
  Ethiopia: "Etiópia",
  Rwanda: "Ruanda",
  Botswana: "Botsuana",
  Comoros: "Comores",
  Gambia: "Gâmbia",
  "Sierra Leone": "Serra Leoa",
  Liberia: "Libéria",
  Niger: "Níger",
  Malawi: "Malawi",
  Burundi: "Burundi",
  "Central African Republic": "Rep. Centro-Africana",
  "South Sudan": "Sudão do Sul",
  Eswatini: "Essuatíni",
  Lesotho: "Lesoto",
  Chad: "Chade",
  Somalia: "Somália",
  "Sao Tome and Principe": "São Tomé e Príncipe",
  Seychelles: "Seicheles",
  Mauritius: "Maurício",
  Djibouti: "Djibuti",
  Eritrea: "Eritreia",

  // Ásia (AFC)
  Japan: "Japão",
  "South Korea": "Coreia do Sul",
  "Korea Republic": "Coreia do Sul",
  "North Korea": "Coreia do Norte",
  "Korea DPR": "Coreia do Norte",
  Iran: "Irã",
  "IR Iran": "Irã",
  "Saudi Arabia": "Arábia Saudita",
  Australia: "Austrália",
  Qatar: "Catar",
  Iraq: "Iraque",
  "United Arab Emirates": "Emirados Árabes Unidos",
  Uzbekistan: "Uzbequistão",
  Jordan: "Jordânia",
  China: "China",
  "China PR": "China",
  Bahrain: "Bahrein",
  Oman: "Omã",
  Kuwait: "Kuwait",
  Syria: "Síria",
  Lebanon: "Líbano",
  Palestine: "Palestina",
  India: "Índia",
  Thailand: "Tailândia",
  Vietnam: "Vietnã",
  Indonesia: "Indonésia",
  Malaysia: "Malásia",
  Philippines: "Filipinas",
  Singapore: "Singapura",
  Myanmar: "Mianmar",
  Tajikistan: "Tajiquistão",
  Turkmenistan: "Turcomenistão",
  "Kyrgyz Republic": "Quirguistão",
  Kyrgyzstan: "Quirguistão",
  Kazakhstan: "Cazaquistão",
  Yemen: "Iêmen",
  Afghanistan: "Afeganistão",
  "Hong Kong": "Hong Kong",
  "Chinese Taipei": "Taipé Chinesa",

  // América do Norte, Central e Caribe (CONCACAF)
  "Costa Rica": "Costa Rica",
  Panama: "Panamá",
  Jamaica: "Jamaica",
  Honduras: "Honduras",
  "El Salvador": "El Salvador",
  Guatemala: "Guatemala",
  Haiti: "Haiti",
  "Trinidad and Tobago": "Trinidad e Tobago",
  Curacao: "Curaçao",
  "Curaçao": "Curaçao",
  Nicaragua: "Nicarágua",
  Suriname: "Suriname",
  Guyana: "Guiana",
  "Dominican Republic": "República Dominicana",
  Cuba: "Cuba",
  Bermuda: "Bermudas",
  Belize: "Belize",
  Grenada: "Granada",
  Barbados: "Barbados",
  "Saint Kitts and Nevis": "São Cristóvão e Névis",
  "Saint Lucia": "Santa Lúcia",
  "Antigua and Barbuda": "Antígua e Barbuda",

  // Oceania (OFC)
  "New Zealand": "Nova Zelândia",
  "New Caledonia": "Nova Caledônia",
  Fiji: "Fiji",
  "Solomon Islands": "Ilhas Salomão",
  "Papua New Guinea": "Papua-Nova Guiné",
  Tahiti: "Taiti",
  Vanuatu: "Vanuatu",
  Samoa: "Samoa",
  Tonga: "Tonga",
};

// Retorna o nome do time em português. Se não houver tradução cadastrada,
// devolve o nome original (em inglês) como fallback — assim nada "some" da
// tela caso a API traga um nome inesperado.
export function traduzirTime(nomeEmIngles: string | null | undefined): string {
  if (!nomeEmIngles) return "";
  return TRADUCOES[nomeEmIngles] ?? nomeEmIngles;
}
